FROM openjdk:21-jdk-slim

WORKDIR /app

# Instalar Maven
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

# Copiar arquivos de configuração do Maven
COPY pom.xml .
COPY src ./src

# Compilar a aplicação
RUN mvn clean package -DskipTests

# Expor a porta
EXPOSE 8081

# Executar a aplicação
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]

